info:
  contact: {}
paths:
  /status:
    get:
      description: Check if the service is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Status
      tags:
      - Status
swagger: "2.0"
